"""Figures for the report. Offline only -- never imported by a view.

Importing matplotlib is slow, so the request path must not touch it. These PNGs
are generated by
`python -m project4.experiments.run_all` and committed alongside the code.
"""

import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

INK = "#1f2933"
MUTED = "#7a8494"
BLUE = "#275CB2"
GREEN = "#1d7a4c"
GRID = "#e2e8f0"


def _style(ax, title, xlabel, ylabel):
    ax.set_title(title, fontsize=12, color=INK, pad=12, loc="left")
    ax.set_xlabel(xlabel, fontsize=10, color=MUTED)
    ax.set_ylabel(ylabel, fontsize=10, color=MUTED)
    ax.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(GRID)
    ax.tick_params(colors=MUTED, labelsize=9)


def recovery_figure(metrics, path):
    r = metrics["recovery"]
    fig, ax = plt.subplots(figsize=(6.4, 3.6), dpi=160)
    x = [b / 60 for b in r["budgets"]]
    for key, colour, label in (("pairwise", BLUE, "Design 1 — pairwise choice"),
                               ("ranking", GREEN, "Design 2 — rank ten")):
        y, sd = r[key], r[f"{key}_sd"]
        ax.plot(x, y, color=colour, linewidth=2, marker="o", markersize=4, label=label)
        ax.fill_between(x, [a - b for a, b in zip(y, sd)], [a + b for a, b in zip(y, sd)],
                        color=colour, alpha=0.12, linewidth=0)
    ax.axvline(5, color=MUTED, linestyle=":", linewidth=1)
    ax.annotate("study budget", (5, ax.get_ylim()[0]), xytext=(5.15, 0.42),
                fontsize=8, color=MUTED)
    _style(ax, "Simulated preference recovery at matched time budgets",
           "elicitation time (minutes)", "Spearman ρ with held-out utility")
    ax.legend(frameon=False, fontsize=9, loc="lower right")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def separability_figure(metrics, path):
    s = metrics["separability"]
    fig, ax = plt.subplots(figsize=(6.4, 3.6), dpi=160)
    colours = [BLUE, GREEN, "#b45309", "#9b2c2c", MUTED]
    for (d, row), colour in zip(sorted(s["table"].items(), key=lambda kv: int(kv[0])), colours):
        ax.plot(s["ns"], row, marker="o", markersize=4, linewidth=2,
                color=colour, label=f"d = {d}")
    ax.axhline(0.5, color=MUTED, linestyle=":", linewidth=1)
    _style(ax, "Why the representation is kept small",
           "number of comparisons collected", "P(data linearly separable)")
    ax.legend(frameon=False, fontsize=9)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def power_figure(metrics, path):
    p = metrics["power"]
    fig, ax = plt.subplots(figsize=(6.4, 3.3), dpi=160)
    ax.bar([str(e) for e in p["effects"]], p["n"], color=BLUE, width=0.6)
    for i, n in enumerate(p["n"]):
        ax.text(i, n + 3, str(n), ha="center", fontsize=9, color=MUTED)
    _style(ax, f"Participants needed (paired test, α={p['alpha']}, power={p['power']})",
           "smallest effect of interest (Cohen's d)", "participants")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def build_all(metrics, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    paths = {}
    for name, fn in (("recovery", recovery_figure),
                     ("separability", separability_figure),
                     ("power", power_figure)):
        path = os.path.join(out_dir, f"{name}.png")
        fn(metrics, path)
        paths[name] = path
    return paths
